ALTER TABLE APPLICATION
ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDATE(candidate_id);

ALTER TABLE APPLICATION
ADD FOREIGN KEY (job_id) REFERENCES JOB(job_id);

ALTER TABLE CANDIDATE
ADD FOREIGN KEY (user_id) REFERENCES USERS(user_id);

ALTER TABLE RECRUITER
ADD FOREIGN KEY (user_id) REFERENCES USERS(user_id);

ALTER TABLE RECRUITER
ADD FOREIGN KEY (company_id) REFERENCES COMPANY(company_id);

ALTER TABLE JOB
ADD FOREIGN KEY (recruiter_id) REFERENCES RECRUITER(recruiter_id);

ALTER TABLE INTERVIEW
ADD FOREIGN KEY (application_id) REFERENCES APPLICATION(application_id);

ALTER TABLE HAS_SKILL
ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDATE(candidate_id);

ALTER TABLE HAS_SKILL
ADD FOREIGN KEY (skill_id) REFERENCES SKILL(skill_id);

ALTER TABLE REQUIRES
ADD FOREIGN KEY (job_id) REFERENCES JOB(job_id);

ALTER TABLE REQUIRES
ADD FOREIGN KEY (skill_id) REFERENCES SKILL(skill_id);

ALTER TABLE USERS
ADD CONSTRAINT chk_user_role CHECK (role IN ('candidate','recruiter','hr','admin'));